site_name: "Chris Merck"
site_description: "Research Notebook"
site_author: "Chris Merck"
site_url: https://chrismerck.github.io
repo_url: https://github.com/chrismerck/chrismerck.github.io

# Use Material for MkDocs to match the look and feel of tinygrad docs
# See https://squidfunk.github.io/mkdocs-material/ for full options

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  logo: assets/favicon.png
  favicon: assets/favicon.png
  palette:
    # Palette toggle for light/dark mode
    - media: "(prefers-color-scheme: light)" # Light mode
      scheme: default
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # Dark mode
      scheme: slate
      primary: grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    # Removing instant navigation which conflicts with MathJax
    # - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    # - navigation.tabs
    # - navigation.tabs.sticky
    - toc.integrate
    - search.highlight
    - search.share
  font:
    # Vintage fonts with 1940s aesthetic:
    text: "Special Elite"  # Classic weathered typewriter font
    #text: "Courier Prime"  # Authentic typewriter font with vintage feel
    #text: "American Typewriter"  # Classic mid-century typewriter style
    #text: "Josefin Slab"  # Elegant vintage slab serif
    #text: "Playfair Display"  # Sophisticated vintage typography
    #text: "Old Standard TT"  # Classic book and newspaper style
    code: "Fira Code"

# Extra CSS files
extra_css:
  - assets/stylesheets/custom.css

nav:
  - Home: index.md
  - Blog:
    - blog/index.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid     # tells SuperFences this block is Mermaid code
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.superfences

plugins:
  - search 
  - blog
  - mermaid2

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js